server {
    listen 80;
    server_name techhub-learn.com www.techhub-learn.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name techhub-learn.com www.techhub-learn.com;

    ssl_certificate /etc/letsencrypt/live/techhub-learn.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/techhub-learn.com/privkey.pem;

    location / {
        proxy_pass http://frontend:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {

        # Handle preflight requests
        if ($request_method = OPTIONS) {
            add_header 'Access-Control-Allow-Origin' $http_origin always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Max-Age' 3600;
            return 204;
        }

        proxy_pass http://backend:5000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        add_header 'Access-Control-Allow-Origin' $http_origin always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
    }

    location /chatbot/ {
        proxy_pass http://chatbot:5001/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}